// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwgrmxrrdzeceimwodgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3Z3JteHJyZHplY2VpbXdvZGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjUyOTYsImV4cCI6MjA2MTQ0MTI5Nn0.XOOZ3imsiJPe7B8Z-yMJC66zuotzkWWxzhA_JcaVluA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);